### ISSUE TITLE
What's the python version?

### ISSUE THREAD

**Issue by LDoubleZhi** [mahyarnajibi/SNIPER#113]
When I use "bash scripts/compile.sh",I found `error:`Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 51, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'``
Is the project use python2.7? Hope your reply soon. Thanks

**Comment by ahaque** [comment]
I got it working with 2.7.

I tried 3.7 but ran into a Cython issue. I also tried 3.6 but ran into compatibility issues.

**Comment by LDoubleZhi** [comment]
@ahaque Thanks, Python 2.7 is worked.
